name: 'Checkout Source'
description: 'Checkout source for jobs triggered by Commit Queue'

runs:
  using: "composite"
  steps:
      - name: Checkout Source
        uses: actions/checkout@v3.5.2
        with:
          ref: ${{ github.event.inputs.revision }}
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: ${{ github.event.inputs.fetch_depth }}
          lfs: true
